global:
  resolve_timeout: 10s
  # smtp_from: prom-demo@sikamail.eu
  # smtp_hello: alertmanager
  # smtp_smarthost: mail.sikamail.eu:587
  # smtp_auth_username: prom-demo@sikamail.eu
  # smtp_auth_password: somesecretpassword
  # smtp_auth_identity: prom-demo@sikamail.eu
  # smtp_require_tls: true
  smtp_from: monitoring@example.com
  smtp_smarthost: maildev.sikademo.com:25
  smtp_require_tls: false

route:
  receiver: mails
  group_by:
    - env
    - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m

receivers:
  - name: mails
    email_configs:
      - send_resolved: true
        to: alert-all@example.com
        # tls_config:
        #   insecure_skip_verify: true
        headers:
          From: monitoring@example.com
          Subject: '{{ template "email.default.subject" . }}'
          To: alert-all@example.com
        html: '{{ template "email.default.html" . }}'
