groups:
  - name: up
    rules:
      - alert: Up
        expr: up == 0
        for: 20s
        labels:
          level: medium
        annotations:
          summary: "Prometheus job {{ $labels.job }} with {{ $labels.instance }} instance is down"
          description: "Job {{ $labels.job }} with {{ $labels.instance }} instance has been down for more than 20 seconds."
