groups:
  - name: up
    rules:
      - alert: up
        expr: probe_success{exported_instance="demo",exported_job="demo"} == 0
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.app }} is down"
          description: "{{ $labels.app }} has been down for more than 20 seconds."
