global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node
    dns_sd_configs:
      - type: A
        port: 9100
        refresh_interval: 10s
        names:
          - example-all.sikademo.com
  - job_name: example
    dns_sd_configs:
      - type: A
        port: 80
        refresh_interval: 10s
        names:
          - example-all.sikademo.com
