services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: grafana

      GF_SERVER_ROOT_URL: http://127.0.0.1:3000
      GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
      GF_AUTH_GENERIC_OAUTH_NAME: 'SSO'
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://sso.sikalabs.com/realms/training/protocol/openid-connect/auth
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://sso.sikalabs.com/realms/training/protocol/openid-connect/token
      GF_AUTH_GENERIC_OAUTH_API_URL: https://sso.sikalabs.com/realms/training/protocol/openid-connect/userinfo
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: example_client_id
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: example_client_secret
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email groups
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME: email
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups[*], 'grafana-admin') && 'Admin'
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: 'true'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_SIGNOUT_REDIRECT_URL: https://sso.sikalabs.com/realms/training/protocol/openid-connect/logout
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
