{
 "title": "Loki Example",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\"loggen.+\"}"
    }
   ]
  },
  {
   "title": "Log rates by app",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate({app=~\"loggen.+\"}[5m])) by (app)"
    }
   ]
  },
  {
   "title": "Log rates by app and level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"ERROR\"[5m])) by (app)",
     "legendFormat": "ERROR {{app}}"
    },
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"WARN\"[5m])) by (app)",
     "legendFormat": "WARN  {{app}}"
    },
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"INFO\"[5m])) by (app)",
     "legendFormat": "INFO  {{app}}"
    },
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"DEBUG\"[5m])) by (app)",
     "legendFormat": "DEBUG  {{app}}"
    }
   ]
  },
  {
   "title": "Cumulative log rates by app and level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"ERROR\"[5m]))",
     "legendFormat": "ERROR"
    },
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"WARN\"[5m]))",
     "legendFormat": "WARN"
    },
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"INFO\"[5m]))",
     "legendFormat": "INFO"
    },
    {
     "expr": "avg(rate({app=~\"loggen.+\"} |= \"DEBUG\"[5m]))",
     "legendFormat": "DEBUG"
    }
   ]
  }
 ]
}