global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: example
    static_configs:
      - targets:
          - metrics-generator:8000

  - job_name: time-exporter
    static_configs:
      - targets:
          - example-time-exporter:8000
