global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - example0.sikademo.com:9100
          - example1.sikademo.com:9100
          - example2.sikademo.com:9100
  - job_name: cadvisor
    static_configs:
      - targets:
          - example0.sikademo.com:9338
          - example1.sikademo.com:9338
          - example2.sikademo.com:9338
  - job_name: random-metrics
    static_configs:
      - targets:
          - example0.sikademo.com:9001
          - example1.sikademo.com:9002
          - example2.sikademo.com:9003
  - job_name: metgen
    static_configs:
      - targets:
          - example0.sikademo.com:9011
          - example1.sikademo.com:9012
          - example2.sikademo.com:9013
